name: infra-deploy-prd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployments/infra
        shell: bash
    environment: production
    env:
      AWS_ACCESS_KEY_ID: "${{secrets.AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY_SECRET }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'

      - name: Install Dependencies
        run: go mod download

      - name: Build Loader
        run: GOARCH=amd64 GOOS=linux go build -o main
        working-directory: ./cmd/lambda/cron_monitor

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -no-color -var environment="prd" -var email_sender="jrolstad@gmail.com" -var google_api_key="${{secrets.GOOGLE_API_KEY}}"